name: Selenium Tests 

on:
  push: 
    branches:
      - main

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Selenium tests  
      run: |
        python Python_projects/python_project/test_checkbox.py
