name: Selenium Tests 

on:
  push: 
    branches:
      - main

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Run Selenium tests  
      run: |
         python /home/runner/work/TestConferenceGuild/Python_projects/python_project/test_checkbox.py
