name: Run Test Checkbox
on:
  # workflow_dispatch: #turn this on if you want to run the job manually  
  push: 
    branches:
      - main
jobs:
  test_checkbox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # - name: Install software
      #   run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest
      - name: Run the PytTest script
        run: pytest -rA
      
