name: Selenium Tests 

on:
  push: 
    branches:
      - main

jobs:

  run-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Selenium tests  
      run: |
         python TestConferenceGuild/Python_projects/python_project/test_checkbox.py
