name: Selenium Tests 

on:
  push: 
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Selenium tests  
      working-directory: /home/runner/work/TestConferenceGuild/Python_projects/python_project_headless/
      run: |
        python test_checkbox_headless.py
